### ISSUE TITLE
Throwing URL parsing error while calling customer profile

### ISSUE THREAD

**Issue by arpit-varshney18** [adobe/aio-lib-customer-profile#62] opened 2023-09-20 17:21 UTC
### Expected Behaviour
Should return a successful response

### Actual Behaviour
Throwing Error

#### Platform and Version
Mac OS used 
"@adobe/aio-sdk": "^4.1.0"
Node.js v20.5.1
NPM version 9.8.0

#### Sample Code that illustrates the problem
const { Core, State, Files, Target, Analytics, CampaignStandard, CustomerProfile, AudienceManagerCD, Events } = require('@adobe/aio-sdk');
async function sdkTest() {
    //initialize sdk
const customerProfileClient = await CustomerProfile.init('<tenant>', '<imsOrgId>', 'x-api-key', '<valid auth token>', '[sandbox]')
     // Customer Profile example
    const profileParams = {
      entityId: 'xyz',
      entityIdNS: 'loyaltyId'
    }
    const customerProfile = await customerProfileClient.getProfile(profileParams)
    console.log(customerProfile);

#### Logs taken while reproducing problem

AioCoreSDKError [CustomerProfileAPIError]: [CustomerProfileAPISDK:ERROR_ENTITIES] Error TypeError: Failed to parse URL from /data/core/ups/access/entities?schema.name=_xdm.context.profile&entityId=079157043&entityIdNS=loyaltyId
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async http (/Users/xxxx/node/node_modules/swagger-client/lib/http/index.js:74:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:405:5)
      at new URL (node:internal/url:778:13)
      at new Request (node:internal/deps/undici/undici:7132:25)
      at fetch2 (node:internal/deps/undici/undici:10715:25)
      at Object.fetch (node:internal/deps/undici/undici:11574:18)
      at fetch (node:internal/process/pre_execution:271:25)
      at http (/Users/xxxx/node/node_modules/swagger-client/lib/http/index.js:74:45)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    input: '/data/core/ups/access/entities?schema.name=_xdm.context.profile&entityId=079157043&entityIdNS=loyaltyId',
    code: 'ERR_INVALID_URL'
  }
}
    at new <anonymous> (/Users/xxx/node/node_modules/@adobe/aio-lib-core-errors/src/AioCoreSDKErrorWrapper.js:33:9)
    at /Users/xxx/node/node_modules/@adobe/aio-lib-customer-profile/src/openApiSDK.js:102:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERROR_ENTITIES',
  sdk: 'CustomerProfileAPISDK',
  sdkDetails: { parameters: { entityId: 'xyz', entityIdNS: 'loyaltyId' } }
}

**Comment by shazron** [comment] 2023-09-21 06:25
Thanks! This is a duplicate of #60

**Closed by shazron** 2023-09-21 06:25 UTC

**Comment by arpit-varshney18** [comment] 2023-09-21 06:31
@shazron Thanks for the update. I can see the PR has been merged. Can you let us know when the new release with the fix is planned?

**Comment by shazron** [comment] 2023-09-21 08:55
Probably tonight, if not Monday. We're working on a further related fix if not it would have already been out.

**Comment by arpit-varshney18** [comment] 2023-09-21 09:30
@shazron Thanks for confirming.

**Comment by MichaelGoberling** [comment] 2023-09-21 14:05
@arpit-varshney18 

FYI - A fix for this has been released in version [2.0.2](https://github.com/adobe/aio-lib-customer-profile/releases/tag/2.0.2)

**Comment by arpit-varshney18** [comment] 2023-09-21 16:04
@MichaelGoberling Great news! Thanks for informing.
